name: dfist19
description: A new Flutter project.

version: 1.0.5+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  shared_preferences: ^0.5.4+5
  add_2_calendar: 1.3.1
  flutter:
    sdk: flutter

  url_launcher: 3.0.0

  cupertino_icons: ^0.1.2

  like_button: ^0.1.9
  pull_to_refresh: ^1.5.7
  onesignal_flutter: ^2.0.0
  http: ^0.12.0+2
  fit_image: ^0.1.2
  font_awesome_flutter: 8.5.0
  json_annotation: ^2.0.0
  jiffy: ^2.1.1
  marquee: ^1.3.1
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  build_runner:
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Black.ttf
        - asset: fonts/NunitoSans-BlackItalic.ttf
        - asset: fonts/NunitoSans-Bold.ttf
        - asset: fonts/NunitoSans-BoldItalic.ttf
        - asset: fonts/NunitoSans-ExtraBold.ttf
        - asset: fonts/NunitoSans-ExtraBoldItalic.ttf
        - asset: fonts/NunitoSans-ExtraLight.ttf
        - asset: fonts/NunitoSans-ExtraLightItalic.ttf
        - asset: fonts/NunitoSans-Italic.ttf
        - asset: fonts/NunitoSans-Light.ttf
        - asset: fonts/NunitoSans-LightItalic.ttf
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-SemiBold.ttf
        - asset: fonts/NunitoSans-SemiBoldItalic.ttf

  assets:
    - assets/logo.png
    - assets/info.png
    - assets/notifications.png
    - assets/tickets.png
    - assets/uniq_map.png
    - assets/gdg_istanbul_logo.png
    - assets/facebook.png
    - assets/github.png
    - assets/instagram.png
    - assets/linkedin.png
    - assets/twitter.png
    - assets/youtube.png
    - assets/red.png
    - assets/web.png
    - assets/cloud.png
    - assets/people.png
    - assets/cat.png
    - assets/question.png
    - assets/newspaper.png
    - assets/uniq.jpeg
    - assets/path.png
    - assets/app_logo.png
    - assets/ic_zeplin.png
    - assets/ic_peak.png
    - assets/ic_google.png
    - assets/ic_jetbrains.png
    - assets/ic_adesso.png
    - assets/ic_pixery.png
    - assets/ic_gcloud.png
    - assets/gtu_kongre_merkezi.jpg
    - assets/empty.png
    - assets/schedule.png